import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Box, Title, Text, Center, Image, Button } from "@mantine/core";
import Navbar from "../components/Navbar";

const CreateResume: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>NextJS Resume Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href="/" passHref>
          <Button size={"xs"} component="a" color={"violet"}>
            Go Back
          </Button>
        </Link>
        <Box>Resume Page</Box>
      </main>
    </Box>
  );
};

export default CreateResume;
