import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Box, Title, Text, Center, Image, Button } from "@mantine/core";
import Navbar from "../components/Navbar";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>NextJS Resume Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Center sx={{ padding: "6rem 0" }}>
          <Box>
            <Title align={"center"} order={1} mb={8}>
              <Text color={"violet"} inherit component={"span"}>
                Build{" "}
              </Text>{" "}
              and{" "}
              <Text color={"violet"} inherit component={"span"}>
                optimize{" "}
              </Text>{" "}
              your developer resume
            </Title>
            <Text align={"center"} mb={32}>
              Completely free to use, create and download Clean ATS-friendly
              resume format to ensure you get seen by recruiters
            </Text>
            <div>
              <Image src="https://kutty.netlify.app/hero.jpg" alt={"hero"} />
            </div>
            <Center mt={16}>
              <Link href="/create-resume" passHref>
                <Button component="a" color={"violet"}>
                  Create Resume
                </Button>
              </Link>
            </Center>
          </Box>
        </Center>
      </main>
    </Box>
  );
};

export default Home;
